export interface CalendarEvent {
    title: string;
    description: string;
    location: string;
    address?: string;
    googleMapsUrl?: string;
    startTime: Date;
    durationMinutes: number;
}

/**
 * Generate an ICS file content from a CalendarEvent
 */
export function generateICS(event: CalendarEvent): string {
    const formatDate = (date: Date) => {
        return date.toISOString().replace(/-|:|\.\d+/g, '');
    };

    const endTime = new Date(event.startTime.getTime() + event.durationMinutes * 60000);

    const descriptionParts = [
        event.description,
        event.address ? `\nAddress: ${event.address}` : '',
        event.googleMapsUrl ? `\nDirections: ${event.googleMapsUrl}` : '',
        '\nGenerated by In. Concierge'
    ].filter(Boolean).join('\n');

    const icsContent = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//In. Social Coordinator//EN',
        'BEGIN:VEVENT',
        `DTSTAMP:${formatDate(new Date())}`,
        `DTSTART:${formatDate(event.startTime)}`,
        `DTEND:${formatDate(endTime)}`,
        `SUMMARY:${event.title}`,
        `DESCRIPTION:${descriptionParts.replace(/\n/g, '\\n')}`,
        `LOCATION:${event.address || event.location}`,
        'END:VEVENT',
        'END:VCALENDAR'
    ].join('\r\n');

    return icsContent;
}

/**
 * Trigger a browser download of an ICS file
 */
export function downloadICS(event: CalendarEvent) {
    const content = generateICS(event);
    const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${event.title.replace(/\s+/g, '_')}.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
