import { Event, User } from './types';

// Sample users
const users: User[] = [
    {
        id: '1',
        name: 'Jane Harris',
        avatar: 'https://i.pravatar.cc/150?img=1',
    },
    {
        id: '2',
        name: 'Alex Chen',
        avatar: 'https://i.pravatar.cc/150?img=2',
    },
    {
        id: '3',
        name: 'Sarah Johnson',
        avatar: 'https://i.pravatar.cc/150?img=3',
    },
    {
        id: '4',
        name: 'Michael Brown',
        avatar: 'https://i.pravatar.cc/150?img=4',
    },
    {
        id: '5',
        name: 'Emma Wilson',
        avatar: 'https://i.pravatar.cc/150?img=5',
    },
];

// Sample events with realistic data
export const mockEvents: Event[] = [
    {
        id: '1',
        title: 'Cevin Sephora',
        description: 'Activist and entrepreneur Cevin Sephora reflects on how to know and be known in a digital age.',
        image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80',
        date: new Date('2026-12-21T19:00:00'),
        endDate: new Date('2026-12-22T22:00:00'),
        location: 'Art Gallery',
        organizer: users[0],
        guests: [users[1], users[2]],
        guestCount: 1456,
        isPublic: true,
        tags: ['Art', 'Gallery', 'Talk'],
        status: 'upcoming',
        size: 'large',
    },
    {
        id: '2',
        title: 'Sunset Rooftop Session',
        description: 'Join us for drinks and music as we watch the sunset from the best rooftop in the city.',
        image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
        date: new Date('2026-01-23T18:00:00'),
        location: 'Downtown Rooftop Bar',
        organizer: users[1],
        guests: [users[0], users[2], users[3]],
        guestCount: 42,
        isPublic: false,
        tags: ['Music', 'Social', 'Drinks'],
        status: 'upcoming',
        size: 'medium',
    },
    {
        id: '3',
        title: 'Morning Yoga & Coffee',
        description: 'Start your weekend right with a relaxing yoga session followed by artisan coffee.',
        image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
        date: new Date('2026-01-25T08:00:00'),
        location: 'Zen Studio',
        organizer: users[2],
        guests: [users[0], users[4]],
        guestCount: 18,
        isPublic: true,
        tags: ['Wellness', 'Morning', 'Coffee'],
        status: 'upcoming',
        size: 'small',
    },
    {
        id: '4',
        title: 'Tech Startup Mixer',
        description: 'Network with founders, investors, and innovators shaping the future of technology.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
        date: new Date('2026-01-26T19:00:00'),
        location: 'Innovation Hub',
        organizer: users[3],
        guests: [users[1], users[2], users[4]],
        guestCount: 127,
        isPublic: true,
        tags: ['Tech', 'Networking', 'Startup'],
        status: 'upcoming',
        size: 'medium',
    },
    {
        id: '5',
        title: 'Underground Jazz Night',
        description: 'Intimate jazz performance in a speakeasy-style venue. Limited capacity.',
        image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80',
        date: new Date('2026-01-28T21:00:00'),
        location: 'The Blue Note',
        organizer: users[4],
        guests: [users[0], users[1], users[3]],
        guestCount: 35,
        isPublic: false,
        tags: ['Music', 'Jazz', 'Nightlife'],
        status: 'upcoming',
        size: 'small',
    },
    {
        id: '6',
        title: 'Street Food Festival',
        description: 'Explore flavors from around the world at this outdoor culinary celebration.',
        image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
        date: new Date('2026-01-30T12:00:00'),
        location: 'Central Park',
        organizer: users[0],
        guests: [users[2], users[3], users[4]],
        guestCount: 892,
        isPublic: true,
        tags: ['Food', 'Festival', 'Outdoor'],
        status: 'upcoming',
        size: 'large',
    },
    {
        id: '7',
        title: 'Midnight Movie Marathon',
        description: 'Classic horror films back-to-back. Bring blankets and snacks!',
        image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80',
        date: new Date('2026-02-01T23:00:00'),
        location: 'Retro Cinema',
        organizer: users[1],
        guests: [users[0], users[4]],
        guestCount: 24,
        isPublic: false,
        tags: ['Movies', 'Horror', 'Late Night'],
        status: 'upcoming',
        size: 'small',
    },
    {
        id: '8',
        title: 'Beach Volleyball Tournament',
        description: 'Teams of 4, prizes for winners, BBQ afterwards. All skill levels welcome.',
        image: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&q=80',
        date: new Date('2026-02-03T14:00:00'),
        location: 'Santa Monica Beach',
        organizer: users[2],
        guests: [users[1], users[3]],
        guestCount: 64,
        isPublic: true,
        tags: ['Sports', 'Beach', 'Competition'],
        status: 'upcoming',
        size: 'medium',
    },
    {
        id: '9',
        title: 'Saturday Night Fever',
        description: 'The peak mood of the week. Dancing and cocktails.',
        image: 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=800&q=80',
        date: new Date('2026-01-17T22:00:00'),
        location: 'Neon Lounge',
        organizer: users[0],
        guests: [users[1], users[2], users[3], users[4]],
        guestCount: 88,
        isPublic: true,
        tags: ['Party', 'Dance', 'Nightlife'],
        status: 'upcoming',
        size: 'large',
        type: 'EVENT',
    },
    {
        id: '10',
        title: 'Sunday Brunch & Mimosa',
        description: 'Recover and relax with friends over a lavish brunch.',
        image: 'https://images.unsplash.com/photo-1513442542250-854d436a73f2?w=800&q=80',
        date: new Date('2026-01-18T11:00:00'),
        location: 'Garden Cafe',
        organizer: users[4],
        guests: [users[0], users[1]],
        guestCount: 12,
        isPublic: false,
        tags: ['Food', 'Social', 'Brunch'],
        status: 'upcoming',
        size: 'medium',
        type: 'EVENT',
    },
    {
        id: '11',
        title: 'Morning Yoga Huddle',
        description: 'Who is down for some early morning yoga in the park?',
        image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
        date: new Date('2026-01-19T08:00:00'),
        location: 'Central Park',
        organizer: users[2],
        guests: [users[0]],
        guestCount: 2,
        isPublic: false,
        tags: ['Wellness', 'Morning'],
        status: 'upcoming',
        size: 'small',
        type: 'HANGOUT',
    },
];

export const getEventById = (id: string): Event | undefined => {
    return mockEvents.find(event => event.id === id);
};

export const getUpcomingEvents = (): Event[] => {
    return mockEvents.filter(event => event.status === 'upcoming');
};
